### ISSUE TITLE
Update OAS3 specification through `update_from_mountable`

### ISSUE THREAD

**Issue by heksesang** [amedia/paperclip#3]
```[tasklist]
### Tasks
- [ ] https://github.com/amedia/paperclip/issues/4
- [ ] https://github.com/amedia/paperclip/issues/5
- [ ] https://github.com/amedia/paperclip/issues/6
```
